name: Gentle_Student
description: An application that makes students engage more in their community.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  map_view: "^0.0.12"
  flutter_html_view: "^0.5.2"
  sqflite: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/crest-gentlestudent.png
    - assets/PrivacyPolicy.txt
    - assets/AboutUs.txt
  fonts:
      - family: NeoSansPro
        fonts:
          - asset: assets/NeoSansPro-Regular.otf