name: Gentle_Student
description: An application that makes students engage more in their community.

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  firebase_core: 0.1.2
  cloud_firestore: 0.3.0
  map_view: "^0.0.12"
  flutter_html_view: "^0.5.2"
  intro_views_flutter: "^2.2.2"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/crest-gentlestudent.png
    - assets/PrivacyPolicy.txt
    - assets/AboutUs.txt

    - assets/tutorial/beacon.png
    - assets/tutorial/bluetooth.png
    - assets/tutorial/challenge.png
  fonts:
      - family: NeoSansPro
        fonts:
          - asset: assets/NeoSansPro-Regular.otf